### ISSUE TITLE
Gitlab OAuth Group Policy

### ISSUE THREAD

**Issue by LucienBrule** [openshift/oauth-server#99]
As a user I would like to be able to limit login from Gitlab to a subset of users, namely users who are part of my gitlab.com group. 

The following would be how I expect this feature to be exposed:

```
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: gitlab 
    mappingMethod: claim 
    type: GitLab
    gitlab:
      clientID: {...} 
      clientSecret: 
        name: gitlab-secret
      url: https://gitlab.com 
      ca: 
        name: ca-config-map
      # by group name
      group: mygroup
      # by email ending
      domain: mydomain.com
```

The Current behaviour is as follows:

Completion of the [latest documentation](https://docs.openshift.com/container-platform/4.9/authentication/identity_providers/configuring-gitlab-identity-provider.html#configuring-gitlab-identity-provider) leaves the cluster open to sign ins from any user of gitlab.com. 

This leaves an issue in that there is no way to control who can sign into a gitlab application from inside gitlab, thus the client must restrict auth.

The current documented solution is to make a mapping method for an identity provider, presumably setting this to lookup as per https://access.redhat.com/solutions/5487011 , which would lead to something like https://access.redhat.com/solutions/5389931 . Mind you the documentation makes no mention of the permissive authentication, while on the google and github providers it is mentioned as a warning.

I found this PR https://github.com/openshift/oauth-server/pull/87 which adds a groupmapper, and found this issue https://issues.redhat.com/browse/RFE-106 which seems to be related. 

Would it be possible to give Gitlab users a way to lock their sign ins to groups that isn't manual?

corresponding support request: https://access.redhat.com/support/cases/#/case/03146331
